spring:
  application:
    name: smart-service-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
